version: '3'
networks:
 dev_planestic:

services:
   ud-repository-files-ms:
     image: planesticud/ud-repository-files-ms
     container_name: ud-repository-files-ms
     restart: on-failure
     env_file:
        - .env
     networks:
        - dev_planestic          

networks:
  dev_planestic:
    external: true
